--- 
- 
  become: true
  hosts: ubuntu
  tasks: 
    # Installs apache, wsgi, python
    - name: "install apache2"
      apt: "name=apache2 update_cache=yes state=latest"
    - name: "install mod_wsgi"
      apt: name=libapache2-mod-wsgi
    - name: "install python-dev"
      apt: name=python-dev
    - name: "installs python setup tools"
      apt: name=python-setuptools
    - name: "install pip"
      apt: name=python-pip
      #Enables WSGI
    - name: "enable a2enmod wsgi"
      shell: a2enmod wsgi


      #Creates directory for the Flask App
    # - name: Creates directory
    #   file:
    #     path: /var/www/FlaskApp
    #     state: directory
    # - name: Creates directory
    #   file:
    #     path: /var/www/FlaskApp/FlaskApp/static
    #     state: directory
    # - name: Creates directory
    #   file:
    #     path: /var/www/FlaskApp/FlaskApp/templates
    #     state: directory

    - git:
        repo: 'https://github.com/{{ github_user }}/{{ app_name }}.git'
        dest: /var/www/{{ app_name }}
        update: yes
      # Installs VENV and requirements and creates venv environment
    - name: Creates directory
      file:
        path: /var/www/{{ app_name }}/FlaskApp
        state: directory
    - name: "install venv"
      pip:
        requirements: /var/www/{{ app_name }}/requirements.txt
        virtualenv: /var/www/{{ app_name }}/FlaskApp/env
        virtualenv_python: python3.8

    # - name: "activate venv" 
    #   shell: . /var/www/FlaskApp/FlaskApp/venv/bin/activate

    # - name: "copy __init__.py"
    #   copy:
    #     src: __init__.py
    #     dest: /var/www/FlaskApp/FlaskApp/__init__.py
    #     mode: '0777'

    - name: "transfer conf file"
      template:
        src: FlaskAppBig.j2
        dest: /etc/apache2/sites-available/FlaskApp.conf
        mode: '0777'
    - name: "transfer wsgi file"
      template:
        src: flaskapp.j2
        dest: /var/www/{{ app_name }}/flaskapp.wsgi
        mode: '0777'
    - shell: /usr/sbin/a2ensite FlaskApp

      # Clean up, deletes apache files that conflict with flask
    - name: Ansible delete directory
      file:
        path: /var/www/html
        state: absent
    - name: Ansible delete file
      file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent
    - name: Ansible delete file
      file:
        path: /etc/apache2/sites-available/default-ssl.conf
        state: absent
    - name: Ansible delete file 
      file:
        path: /etc/apache2/sites-available/000-default.conf
        state: absent
    - name: "Restart apache"
      systemd:
        name: apache2
        daemon_reload: yes
        state: restarted
...

